//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disi.Services.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public int Id { get; set; }
        public string Dni { get; set; }
        public System.DateTime FechaFirma { get; set; }
        public int TiempoSegIniciofirma { get; set; }
        public int TiempoSegFinFirma { get; set; }
        public Nullable<int> TiempoMiliSegInicioFirma { get; set; }
        public Nullable<int> TiempoMiliSegFinFirma { get; set; }
        public string UrlImagen { get; set; }
    }
}
