source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("EBImage")
library("EBImage")
Image <- readImage("Images/imagen1.png")
Image2 <- readImage("Images/imagen2.png")
Image3 <- readImage("Images/imagen3.png")
#display(Image)
print(Image)
print(Image2)
print(Image3)